### ISSUE TITLE
Save output as file

### ISSUE THREAD

**Issue by AXYZE9** [shashikg/WhisperS2T#10]
Hey, is there a way to save output as file (json/vtt/srt)?

I've tried doing that yesterday using f.write, but failed to do so.
I have completly zero experience with Python, so this may be easy... or may be not.

I was used to whisper CLI tools, but I wanted to see if WhisperS2T is faster than insanely-fast-whisper.

**Comment by shashikg** [comment]
Hi @AXYZE9 I have added this feature in this PR https://github.com/shashikg/WhisperS2T/pull/13

Uninstall your current installation and install using following command: `pip install -U git+https://github.com/shashikg/WhisperS2T.git` 

Usage:
```py
files = ['file.wav']
lang_codes = ['en']
tasks = ['transcribe']
initial_prompts = [None]

out = model.transcribe_with_vad(files,
                                lang_codes=lang_codes,
                                tasks=tasks,
                                initial_prompts=initial_prompts,
                                batch_size=24)

whisper_s2t.write_outputs(out, format='vtt', ip_files=files, save_dir="./save_dir") # Save outputs
```

For custom output file names:

```py
whisper_s2t.write_outputs(out, format='vtt', op_files=op_files)
```

Supported formats: `vtt, srt, json, tsv`.

**Comment by shashikg** [comment]
Hi @casic 

Yes, alignment is supported. Check these:
https://github.com/shashikg/WhisperS2T/releases/tag/v1.2.0
https://github.com/shashikg/WhisperS2T?tab=readme-ov-file#ctranslate2-backend
