### ISSUE TITLE
Question : How do i use it without the VAD

### ISSUE THREAD

**Issue by Govind-S-B** [shashikg/WhisperS2T#14]
I am trying to use this project for translating a malayalam real world noise audio that i have to english . the VAD filter filters away a lot of important information as well , so i wanted to test things with it disabled . But the `transcribe` function requires a few extra parameters and I go no idea how to extract those out of the pipe that you built

**Comment by shashikg** [comment]
Hi @Govind-S-B, can you try tweaking the VAD parameters? For example:

```py
speech_segmenter_options = {
    'eos_thresh': 0.1,
    'bos_thresh': 0.1,
}

model = whisper_s2t.load_model(speech_segmenter_options=speech_segmenter_options)
```

The current VAD model is trained using the following languages:  English, German, Mandarin, French, Russian, and Spanish.

**Comment by shashikg** [comment]
Fixed in this PR: https://github.com/shashikg/WhisperS2T/pull/15

Uninstall the current installation and install using following command: `pip install -U git+https://github.com/shashikg/WhisperS2T.git`. 

Use `model.transcribe` instead of `model.transcribe_with_vad`

**Comment by shashikg** [comment]
Hi @Govind-S-B can you check and confirm what's the accuracies you are getting now?
