### ISSUE TITLE
great project, wondering if it supports ctranslate 4.0 and cuda 12+

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#16]
Just came across your project.  Plan on trying out as a replacement, but I was wondering if it supports the new ctranslate4.0 and cuda 12+ by chance??

**Comment by shashikg** [comment]
Hey @BBC-Esq I think you mean CTranslate2 4.0.0 right? Yes, it should support. 

I'm closing the issue, feel free to reopen if you are facing any issue while using this package with CTranslate2 4.0.0
