### ISSUE TITLE
CUDA 11.8 support please?

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#18]
I tried running using CUDA 11.8 that's already installed on my computer, but it state that it needed cublas64_12.dll or what not...whereas CUDA 11.8 uses cublas64_11.dll.  I had to locate the newer cublas version within a python wheel and put that in my system PATH.  Is there a way to allow CUDA 11.8 support as well?

**Comment by shashikg** [comment]
It should support cuda 11.8. Before installing this package install torch, CTranslate2, etc for CUDA 11.8. Then make sure to install whispers2t without upgrade command, otherwise most probably it will again upgrade other packages for cuda 12.

**Comment by BBC-Esq** [comment]
Got it!  Will close out the issue and seek reopening if it doesn't work.
