### ISSUE TITLE
support for word timestamps

### ISSUE THREAD

**Issue by eschmidbauer** [shashikg/WhisperS2T#2]
I cannot figure out how to enable word-level timestamps. 
I have tried the following with `CTranslate2`
```python
import whisper_s2t

model = whisper_s2t.load_model(model_identifier="large-v2", backend='CTranslate2', asr_options={"word_timestamps":True})

files = ['test.wav']
lang_codes = ['en']
tasks = ['transcribe']
initial_prompts = [None]
out = model.transcribe_with_vad(files, lang_codes=lang_codes, tasks=tasks, initial_prompts=initial_prompts, batch_size=32)
```

**Comment by eschmidbauer** [comment]
```
out[0][0]
{'text': 'She concluded that she must have mistaken some other sound for that of the human voice, or else that it was altogether in her fancy.', 'avg_logprob': -0.19695881328412465, 'no_speech_prob': 0.0018739700317382812, 'start_time': 0.0, 'end_time': 7.12}
```

**Comment by shashikg** [comment]
Hi @eschmidbauer 

Word-level alignment is not supported at present. I am researching some optimal methods for that (in progress).

**Comment by shashikg** [comment]
Hi @eschmidbauer 

Closing this issue. I have added the word alignment feature in the latest release: https://github.com/shashikg/WhisperS2T/releases/tag/v1.2.0

**Comment by shashikg** [comment]
Hi @eschmidbauer

Closing this issue. I have added the word alignment feature in the latest release: https://github.com/shashikg/WhisperS2T/releases/tag/v1.2.0
