### ISSUE TITLE
huggingface repository for ctranslate2 models or provide as alternative source

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#20]
Again, I am extremely impressed by this program.  I've been pining for a long time for something that can do batch processing based on ctranslate2, especially since huggingface claimed to have the fastest implemantation.

What are your thoughts about a pull request to change the ```hf_utils.py``` script to list my repository for all various quantizations of the whisper models?

https://huggingface.co/ctranslate2-4you

I realize the ctranslate2 can quantize at runtime, but it does take some additional time and I figured users might want the option.  Alternatively, would you be willing to a pull request on your repository linking my huggingface repository as an alternative source to the default "systran" models?

The difference is I've quantized every whisper model size to every ctranslate2 available quantization (except ```int16``` of course)...EXCEPT large-v3 since I've noticed regressions with it.  Either way, great job and I'm excited to include it into my programs!

If you're a visual person, here's an example of just my conversions of the large-v2 model:

![image](https://github.com/shashikg/WhisperS2T/assets/108230321/14a31cb6-c989-4bac-b56d-8af7ea3ca26d)

**Comment by shashikg** [comment]
Hi can you check and report here -- what is the difference in load time for loading from float16 exported model vs int8 exported model when using int8 precision.

**Comment by BBC-Esq** [comment]
> Hi can you check and report here -- what is the difference in load time for loading from float16 exported model vs int8 exported model when using int8 precision.

It'll depend on the GPU.  I have a 4090.  Unfortunately I don't have my old script anymore since I already did this testing and made the changes to my program...However, if you'll tell me how to specify a directory instead of automatically downloading the ctranslate2 checkpoints in this script, I can re-test.

Also, I would add that my repository has the ```btloat16``` and ```float32``` ctranslate2 versions.  I've found, for example, that the ```tiny``` model run in ```float32``` is about the same as ```medium``` in ```float16```...while using less vram.  So there's an advantage there.

Also, if a user wants to use ```bfloat16``` instead of ```float16``` (e.g. with newer gpus that support that compute level), converting at runtime from ```float16``` to ```bfloat``` results in "slightly" lower quality.  Ideally, you'd want to use the ```float32``` model converted to ```bfloat16``` at runtime...or simply use the ```bfloat16``` model from the beginning.

Anyhow, here's the script:

```
import whisper_s2t
from whisper_s2t.backends.ctranslate2.model import BEST_ASR_CONFIG, FAST_ASR_OPTIONS

model_kwargs = {
    'compute_type': 'float16',
    #'asr_options': BEST_ASR_CONFIG
    'asr_options': FAST_ASR_OPTIONS
}

model = whisper_s2t.load_model(model_identifier="large-v2", backend='CTranslate2', **model_kwargs)

files = ['test_audio_flac.flac']
lang_codes = ['en']
tasks = ['transcribe']
initial_prompts = [None]

out = model.transcribe_with_vad(files,
                                lang_codes=lang_codes,
                                tasks=tasks,
                                initial_prompts=initial_prompts,
                                batch_size=20)

# Concatenate the text from all utterances
transcription = " ".join([_['text'] for _ in out[0]]).strip()

with open('transcription.txt', 'w') as f:
    f.write(transcription)
```

**Comment by BBC-Esq** [comment]
Can you please tell me how to load a model from a directory?

**Comment by shashikg** [comment]
> Can you please tell me how to load a model from a directory?

```py
model = whisper_s2t.load_model(model_identifier="large-v2", backend='CTranslate2')
```
Here `model_identifier` supports three different values for CTranslate2 and HuggingFace backend. `model_name`, `local_path`, or `hf_repo_id`. 

So, in your case simply this should work: 
```py
model = whisper_s2t.load_model(model_identifier="ctranslate2-4you/whisper-large-v2-ct2-int8_float16", backend='CTranslate2', compute_type='int8')
```

Or to load from local directory: 
```py
model = whisper_s2t.load_model(model_identifier="your_local_path_to_model_files", backend='CTranslate2')
```

To get the path where the downloaded model got saved: `print(model.model_path)`

PS: I'm working on detailed docs along with couple of other minor features.. most probably will update those by end of this month.

**Comment by BBC-Esq** [comment]
Thanks, I'll try to get the conversion times for you as you asked.  What did you think about my other reasons for including a wide variety of quantizations for the whisper models?  Or do you only want to change things if there's a significant load time?  I figured your program could continue to rely on the systran models, but offer users another option at least...

**Comment by shashikg** [comment]
> Or do you only want to change things if there's a significant load time?

Yes, if there's isn't any significant difference in **load_time** or **inference_time** or **accuracy**. I think it won't make sense to target different repository for different configurations. If anyone want to still use any other repo, they can still use it by passing the specific repo_id instead of just model name.

In future actually I am planning to remove systran links as well. Working on unified tarred representation for different backends, which can be easily saved as some exported model like: `whisper_large_ct2_int8.wst`. It is a part of this: https://github.com/shashikg/WhisperS2T/issues/8#issuecomment-1919818938

**Comment by BBC-Esq** [comment]
Closing for lack of interest.
