### ISSUE TITLE
tensorrt failures

### ISSUE THREAD

**Issue by colinator** [shashikg/WhisperS2T#21]
If I install your pinned version of tensorrt (0.8.0.dev2024012301 - from your 'install_tensorrt.sh' file), then I get an undefined symbol when I load the model

`model = whisper_s2t.load_model(model_identifier="large-v2", backend='TensorRT-LLM')`

I get 

`ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9is_pinned4callERKNS_6TensorEN3c108optionalINS5_6DeviceEEE.`

If I don't use the pinned version (I just use -pre), then I get a different error:

```
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/attention.py", line 1174, in forward
    assert qkv.ndim() == 2
AssertionError
```

... so just having some trouble getting the tensorrt thing to work. Your idea of providing a dockerfile would probably help a bunch...

**Comment by shashikg** [comment]
And yes I will be adding a dockerfile.

**Comment by shashikg** [comment]
Yeah it seems like C binding for pytorch is creating issue. Can you try this: `pip install -U torch==2.1.2`, if it resolves the issue?

**Comment by colinator** [comment]
Wow, impressive debug there, that totally worked! Here's a starter docker file (required a few more pip installs):

```
FROM nvidia/cuda:12.1.1-devel-ubuntu22.04
RUN apt-get update && apt-get -y install python3.10 python3-pip git libsndfile1 ffmpeg
RUN pip3 install -U torch==2.1.2 git+https://github.com/shashikg/WhisperS2T.git platformdirs cython rich pynvml
COPY code/install_tensorrt.sh /app/install_tensorrt.sh
RUN bash /app/install_tensorrt.sh
```

I'll let you close this issue. Thanks!

**Comment by shashikg** [comment]
@colinator https://github.com/shashikg/WhisperS2T?tab=readme-ov-file#from-docker-container
