### ISSUE TITLE
Batch Transcribing

### ISSUE THREAD

**Issue by vidalfer** [shashikg/WhisperS2T#26]
In your example: 

```
import whisper_s2t

model = whisper_s2t.load_model(model_identifier="large-v2", backend='CTranslate2')

files = ['data/KINCAID46/audio/1.wav']
lang_codes = ['en']
tasks = ['transcribe']
initial_prompts = [None]

out = model.transcribe_with_vad(files,
                                lang_codes=lang_codes,
                                tasks=tasks,
                                initial_prompts=initial_prompts,
                                batch_size=32)

print(out[0][0])
"""
[Console Output]

{'text': "Let's bring in Phil Mackie who is there at the palace. We're looking at Teresa and Philip May. Philip, can you see how he's being transferred from the helicopters? It looks like, as you said, the beast. It's got its headlights on because the sun is beginning to set now, certainly sinking behind some clouds. It's about a quarter of a mile away down the Grand Drive",
 'avg_logprob': -0.25426941679184695,
 'no_speech_prob': 8.147954940795898e-05,
 'start_time': 0.0,
 'end_time': 24.8}
"""
```

The method "transcribe_with_vad" accepts a list of files, but when I try to use a list, only the first audio is transcribed. Does this implementation not support batch transcription?

**Comment by vidalfer** [comment]
Hi @shashikg, thank you for the fast feedback!

Yes, out is a list of lists, and I tried the same thing that you showed me before I opened this issue, but the problem persists :(. I'm testing a list with differents numbers of audios and the first audio is always transcribed, but the others generate empty lists.

Output example with 3 audios:
  {'text': 'Por favor, avalie com uma nota, de 1 a 5, o profissional que lhe atendeu. Obrigado por participar da nossa pesquisa de satisfação.',
   'avg_logprob': -0.04440132106997465,
   'no_speech_prob': 0.003482818603515625,
   'start_time': 313.48,
   'end_time': 323.593}],
 [],
 []]

**Comment by shashikg** [comment]
Weird, it's highly unlikely to get an empty list as output. Are you sure you are using correct lang_codes and non_empty audio files? 

Also please add the exact script that you used. If possible share the audio files. Best will be to share a colab file to reproduce it.

**Comment by vidalfer** [comment]
I found what was wrong:

Actual code (working):

```
import whisper_s2t
model = whisper_s2t.load_model(model_identifier="large-v3", backend='CTranslate2')
files = ['/content/audios/raw_mp3/0648cb64-8a41-4b99-bb9c-c0fbfa5ac655.mp3','/content/audios/raw_mp3/07be489d-8f3d-4a69-ab9a-d0b6ef7065fa.mp3']
tasks = ['transcribe','transcribe']
initial_prompts = [None,None]
lang_codes = ['pt','pt']
out = model.transcribe_with_vad(files,
                                lang_codes=lang_codes,
                                tasks=tasks,
                                initial_prompts=initial_prompts,
                                batch_size=24)
```

My wrong code (before the alteration):

```
import whisper_s2t
model = whisper_s2t.load_model(model_identifier="large-v3", backend='CTranslate2')
files = ['/content/audios/raw_mp3/0648cb64-8a41-4b99-bb9c-c0fbfa5ac655.mp3','/content/audios/raw_mp3/07be489d-8f3d-4a69-ab9a-d0b6ef7065fa.mp3']
tasks = ['transcribe']
initial_prompts = [None]
lang_codes = ['pt']
out = model.transcribe_with_vad(files,
                                lang_codes=lang_codes,
                                tasks=tasks,
                                initial_prompts=initial_prompts,
                                batch_size=24)
                                
```

I'm used to other whisper implementations that only need to pass the language code and the task once. In this implementation, it is necessary to pass according to the number of audios. Now it's working normally

**Comment by shashikg** [comment]
Hey yep you need to pass lang_code for each files individually. This is to allow the following feature which is not supported by other implementations and thus they need lang_code only once. You can also use something like this: `['en', 'pt']` 

**Batching Support with Multiple Language/Task Decoding:** Decode multiple languages or perform both transcription and translation in a single batch for improved versatility and transcription time.
