### ISSUE TITLE
Support for custom audio file

### ISSUE THREAD

**Issue by johnrachwan123** [shashikg/WhisperS2T#3]
When I try to run the pipeline on the following file: https://huggingface.co/datasets/reach-vb/random-audios/resolve/main/sam_altman_lex_podcast_367.flac

I get the following error

```File /nfs/students/rachwan/miniconda3/envs/pruna_pypi/lib/python3.9/site-packages/whisper_s2t/audio.py:30, in load_audio(input_file, sr, return_duration)
     27 wav_file = f"{tmpdir}/tmp.wav"
     28 os.system(f'ffmpeg -hide_banner -loglevel panic -i {input_file} -threads 1 -acodec pcm_s16le -ac 1 -af aresample=resampler=soxr -ar {sr} {wav_file} -y')
---> 30 with wave.open(wav_file, 'rb') as wf:
     31     frames = wf.getnframes()
     32     x = wf.readframes(int(frames))

File /nfs/students/rachwan/miniconda3/envs/pruna_pypi/lib/python3.9/wave.py:509, in open(f, mode)
    507         mode = 'rb'
    508 if mode in ('r', 'rb'):
--> 509     return Wave_read(f)
    510 elif mode in ('w', 'wb'):
    511     return Wave_write(f)

File /nfs/students/rachwan/miniconda3/envs/pruna_pypi/lib/python3.9/wave.py:163, in Wave_read.__init__(self, f)
    161 # else, assume it is an open file object already
    162 try:
--> 163     self.initfp(f)
    164 except:
    165     if self._i_opened_the_file:

File /nfs/students/rachwan/miniconda3/envs/pruna_pypi/lib/python3.9/wave.py:128, in Wave_read.initfp(self, file)
    126 self._convert = None
    127 self._soundpos = 0
--> 128 self._file = Chunk(file, bigendian = 0)
    129 if self._file.getname() != b'RIFF':
    130     raise Error('file does not start with RIFF id')

File /nfs/students/rachwan/miniconda3/envs/pruna_pypi/lib/python3.9/chunk.py:63, in Chunk.__init__(self, file, align, bigendian, inclheader)
     61 self.chunkname = file.read(4)
     62 if len(self.chunkname) < 4:
---> 63     raise EOFError
     64 try:
     65     self.chunksize = struct.unpack_from(strflag+'L', file.read(4))[0]

EOFError:
```

Any idea why this could be happening ?

**Comment by shashikg** [comment]
Hi @johnrachwan123 

Custom audio file is supported, did you install ffmpeg?

**Comment by johnrachwan123** [comment]
Yes I do have ffmpeg installed, does the audio file I linked work for you ?

**Comment by shashikg** [comment]
Hey yep, I think the linked audio file is the one used in the insanely-fast whisper repo, correct? 

Whatever audio codec works with ffmpeg should work. Can you share the output of the following commands? `which ffmpeg` and `ffmpeg -version`

**Comment by johnrachwan123** [comment]
Yes its correct that it is the same audio file used in insanely-fast-whisper. This is the output of the commands you requested:

<img width="1179" alt="Screenshot 2023-12-22 at 12 51 27" src="https://github.com/shashikg/WhisperS2T/assets/43934839/ec9379d2-91ad-4c74-a237-d213cd7c5e9c">

**Comment by shashikg** [comment]
ffmpeg installation seems to be okay. Can you run following two commands in your notebook?

`os.system(f'ffmpeg -i sam_altman_lex_podcast_367.flac -threads 1 -acodec pcm_s16le -ac 1 -af aresample=resampler=soxr -ar 16000 sam_altman_lex_podcast_367.wav')` 

`os.system(f'ffmpeg -i sam_altman_lex_podcast_367.flac -threads 1 -acodec pcm_s16le -ac 1 -af -ar 16000 sam_altman_lex_podcast_367.wav')`

**Comment by johnrachwan123** [comment]
It fails with the following error:

<img width="1366" alt="Screenshot 2023-12-22 at 13 08 14" src="https://github.com/shashikg/WhisperS2T/assets/43934839/ae9d83c8-7823-41b4-a48b-34b3e821373e">

**Comment by shashikg** [comment]
I see.. its because of sox resampler. Can you check if this is working: `os.system(f'ffmpeg -i sam_altman_lex_podcast_367.flac -threads 1 -acodec pcm_s16le -ac 1 -ar 16000 sam_altman_lex_podcast_367.wav -y')` 
?

Also try once removing ffmpeg and reinstall it. Normally ffmpeg binaries contains the sox resampler by default. Your compiled ffmpeg version seems different as well, normally it should be something like this: `ffmpeg version X.X.X` if you are installing it on ubuntu.

**Comment by shashikg** [comment]
HI @johnrachwan123 

Can you check if it's working for you after the following commit? 

https://github.com/shashikg/WhisperS2T/commit/abe4dcb9ce643c9638773ebf1e89de2847cc6266

**Comment by johnrachwan123** [comment]
Both ```os.system(f'ffmpeg -i sam_altman_lex_podcast_367.flac -threads 1 -acodec pcm_s16le -ac 1 -ar 16000 sam_altman_lex_podcast_367.wav -y')``` and the new commit work :) 

Thanks a lot of your help! Closing the issue.
