### ISSUE TITLE
running on macos without cuda

### ISSUE THREAD

**Issue by appsmartsoftware** [shashikg/WhisperS2T#41]
Hello,

Is it possible to run the project on macos, with CTranslate2 backend, without Cuda support for testing on the local environment?

Thx

**Comment by shashikg** [comment]
`model = whisper_s2t.load_model(model_identifier="tiny", backend='CTranslate2', device='cpu', compute_type='int8')`

or

`model = whisper_s2t.load_model(model_identifier="tiny", backend='CTranslate2', device='cpu', compute_type='float32')`
