### ISSUE TITLE
ffmpeg issue - semi-IMPORTANT

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#42]
When trying to transcribe to a VTT file, for example, I get errors when the file to be transcribed has spaces in its name.  I took some time to pinpoint this issue.  Apparently, it's because ```audio.py``` uses os.system to run certain ffmpeg commands and not subprocess.run, for example.  Apparently, when os.system is used with ffmpeg there's a problem when a file to be transcribed has spaces in it.

For example:

"audio - recording for client.mp3"

According to gpt...the problematic line is:

```ret_code = os.system(f'ffmpeg -hide_banner -loglevel panic -i "{input_file}" -threads 1 -acodec pcm_s16le -ac 1 -af aresample=resampler={RESAMPLING_ENGINE} -ar {sr} "{wav_file}" -y')```

Here is the relevant portions of the traceback...I didn't include the entire paths for privacy reasons.  Hope it helps though.   ```whispers2t_batch.py``` refers to my script that's supposed to batch process all files in a directory.  It works perfectly if I remove all files with spaces in their names...

```site-packages\whisper_s2t\audio.py", line 32, in load_audio
    with wave.open(input_file, 'rb') as wf:```

```Python311\Lib\wave.py", line 631, in open
    return Wave_read(f)```

```Python311\Lib\wave.py", line 283, in __init__
    self.initfp(f)```

```Python311\Lib\wave.py", line 250, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id```

```During handling of the above exception, another exception occurred:```

```whispers2t_batch.py", line 58, in <module>
    transcribe_audio_files(audio_files_directory)```

```whispers2t_batch.py", line 46, in transcribe_audio_files
    out = model.transcribe_with_vad([audio_file], lang_codes=lang_codes, tasks=tasks, initial_prompts=initial_prompts, batch_size=70)```

```site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)```

```site-packages\whisper_s2t\backends\__init__.py", line 169, in transcribe_with_vad
    for signals, prompts, seq_len, seg_metadata, pbar_update in self.data_loader(audio_files, lang_codes, tasks, initial_prompts, batch_size=batch_size):```

```site-packages\whisper_s2t\data.py", line 212, in get_data_loader_with_vad
    for file_id, (audio_signal, lang, task, initial_prompt) in enumerate(zip(audio_batch_generator(audio_files), lang_codes, tasks, initial_prompts)):```

```Python311\Lib\multiprocessing\pool.py", line 873, in next
    raise value```

```Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))```

```whisper_s2t\audio.py", line 42, in load_audio
    if ret_code != 0: raise RuntimeError("ffmpeg failed to resample the input audio file, make sure ffmpeg is compiled properly!")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ffmpeg failed to resample the input audio file, make sure ffmpeg is compiled properly!```

**Comment by BBC-Esq** [comment]
A temporary workaround is to convert/copy all files to be process to "temporary files" with no spaces, remember the original file name, create the transcription for the temporary file, but name the VTT for after the original file name.

This workaround solved any and all issues and even files with spaces in their names were processed, albeit indirectly...

**Comment by BBC-Esq** [comment]
Here's the entire script with the workaround:

```
from pathlib import Path
import subprocess
import glob
import whisper_s2t
import shutil
import tempfile

def transcribe_audio_files(directory):
    model_kwargs = {
        'compute_type': 'float16',
        'asr_options': {
            "beam_size": 5,
            "best_of": 1,
            "patience": 2,
            "length_penalty": 1,
            "repetition_penalty": 1.01,
            "no_repeat_ngram_size": 0,
            "compression_ratio_threshold": 2.4,
            "log_prob_threshold": -1.0,
            "no_speech_threshold": 0.5,
            "prefix": None,
            "suppress_blank": True,
            "suppress_tokens": [-1],
            "without_timestamps": False,
            "max_initial_timestamp": 1.0,
            "word_timestamps": True,
            "sampling_temperature": 1.0,
            "return_scores": True,
            "return_no_speech_prob": True,
            "word_aligner_model": 'tiny',
        },
        "device": "cuda",
    }

    model = whisper_s2t.load_model(model_identifier="medium.en", backend='CTranslate2', **model_kwargs)

    directory_path = Path(directory)
    patterns = ['*.mp3', '*.wav', '*.flac']
    audio_files = []

    for pattern in patterns:
        audio_files.extend(directory_path.glob(pattern))

    for original_audio_file in audio_files:
        print(f"Processing {original_audio_file}...")

        with tempfile.NamedTemporaryFile(delete=False, suffix=original_audio_file.suffix) as tmp_file:
            shutil.copy2(original_audio_file, tmp_file.name)
            temp_audio_file_path = Path(tmp_file.name)
        
        lang_codes = ['en']
        tasks = ['transcribe']
        initial_prompts = [None]

        out = model.transcribe_with_vad([str(temp_audio_file_path)], lang_codes=lang_codes, tasks=tasks, initial_prompts=initial_prompts, batch_size=70)

        vtt_file_path = original_audio_file.with_suffix('.vtt')
        whisper_s2t.write_outputs(out, format='vtt', op_files=[str(vtt_file_path)])
        print(f"Transcribed {original_audio_file} to {vtt_file_path}")

        temp_audio_file_path.unlink()

audio_files_directory = r"[PATH TO DIRECTORY OF FILES TO PROCESS" # RAW STRING WAS NECESSARY ON WINDOWS AS WELL...
transcribe_audio_files(audio_files_directory)
```

**Comment by shashikg** [comment]
Can you run this in your terminal and send me the output:

`ret_code = os.system(f'ffmpeg -hide_banner -loglevel panic -i "test 1.mp3" -threads 1 -acodec pcm_s16le -ac 1 -af aresample=resampler=swr -ar 16000 "test.wav" -y')` -- on my machine this runs without any issue.

**Comment by BBC-Esq** [comment]
> Can you run this in your terminal and send me the output:
> 
> 
> 
> `ffmpeg -hide_banner -loglevel panic -i "test 1.mp3" -threads 1 -acodec pcm_s16le -ac 1 -af aresample=resampler=swr -ar 16000 "test.wav" -y` -- on my machine this runs without any issue.

Sure, when I get back to the office I will. Can you explain what we are doing so I can understand?

**Comment by BBC-Esq** [comment]
> Can you run this in your terminal and send me the output:
> 
> `ffmpeg -hide_banner -loglevel panic -i "test 1.mp3" -threads 1 -acodec pcm_s16le -ac 1 -af aresample=resampler=swr -ar 16000 "test.wav" -y` -- on my machine this runs without any issue.

This command worked to convert the .mp3 file.

**Comment by shashikg-triomics** [comment]
Hi @BBC-Esq  please check if your local files are up to date with the main branch: https://github.com/shashikg/WhisperS2T/pull/38/files

**Comment by shashikg** [comment]
Hi @BBC-Esq please make sure your local file is up to date with the main branch:

https://github.com/shashikg/WhisperS2T/pull/38/files

**Comment by BBC-Esq** [comment]
Thanks @shashikg , how can I do that if an updated version hasn't been uploaded to pypi.org yet?

**Comment by shashikg** [comment]
Hi you can install using this: `pip install -U git+https://github.com/shashikg/WhisperS2T.git`

**Comment by BBC-Esq** [comment]
Can I not install any dependencies?  I've been using the "no dependencies" flag and then installing the dependencies manually because my other libraries require certain versions...

**Comment by shashikg** [comment]
Same answer: https://github.com/shashikg/WhisperS2T/issues/29#issuecomment-1958098134

Install with no dependencies and the make sure all the requirements are installed.

**Comment by BBC-Esq** [comment]
Having the most recent code not yet released on pypi.org fixed the issue.  Thanks.  Please consider adding a 0.0.1 update or something to pypi.org.

Also, are you open to pull requests of sample scripts created by the community because I'd like to share my script that recursively processes all files from a specified directory and all sub-directories?  Perhaps in an ```community_examples``` folder?

Also, it's nice that the check for ffmpeg isn't being displayed anymore...Thanks for that.

**Comment by BBC-Esq** [comment]
![image](https://github.com/shashikg/WhisperS2T/assets/108230321/873c8491-be20-4c92-aa5b-1a0de26bd4da)
