### ISSUE TITLE
temp directory absolutely necessary?

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#43]
Is the variable for temp directory here absolutely necessary?

```tmpdir```

The reason I ask is because on my Windows system my "User" environment variables have ```TEMP``` and ```TMP```.   My "System" variables have ```TEMP```, ```TMP```, and ```TMPDIR```.

My ```TMPDIR``` is specific to a PDF-related program (Wondershare) for some reason whereas the other two are generally where all temp files go...which makes me wonder why you didn't use the "standard" or more widely used variable for the temp directory?  Moreover, ```TMPDIR``` isn't even listed as an environment variable for "User" but it is for "System"...

![image](https://github.com/shashikg/WhisperS2T/assets/108230321/89992f7a-8c6e-4522-9104-13faa59c8824)

**Comment by shashikg** [comment]
Hi @BBC-Esq I'm using `tempfile.TemporaryDirectory()` for temp directory, a pretty standard way to create temp directory in python. This always gives a directory inside your system temporary directory.

**Comment by BBC-Esq** [comment]
Not a big deal...thus, closing out.
