### ISSUE TITLE
community integrations portion of readme please?

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#44]
Would you be willing to add a community integrations section of the readme like ```faster-whisper``` has done?  I have a new repository I'd like to add if so!

https://github.com/BBC-Esq/WhisperS2T-batch-transcriber

**Comment by shashikg** [comment]
Hey sure I will consider adding community integration in Readme (I will create a guideline on how to create MR for that). By the way the above repo is misleading. WhisperS2T already supports batch transcription. Maybe rename it to something like WhisperS2T-GUI, WhisperS2T-GUI-Windows? 

Also your implementation is not the correct way to use this package...

https://github.com/BBC-Esq/WhisperS2T-batch-transcriber/blob/main/whispers2t_batch.py#L51

^^ it should be like this (will give better transcription speed):

```py
audio_files = [str(_) for _ in audio_files]
vtt_file_paths = [str(_).with_suffix('.vtt') for _ in audio_files]

lang_codes = 'en'
tasks = 'transcribe'
initial_prompts = None
out = model.transcribe_with_vad(audio_files, lang_codes=lang_codes, tasks=tasks, initial_prompts=initial_prompts, batch_size=70)
whisper_s2t.write_outputs(out, format='vtt', op_files= vtt_file_paths)
```

**Comment by BBC-Esq** [comment]
Wow, thanks for the tips.  I thought it already supported batch transcription but wasn't sure how to implement it.  I'll redo the script and consider renaming the repo.  Why do you suggest not naming it something mentioning "batch?"  Is it because you feel it infringes on recognizing that batch already exists, and improperly implies that I created that feature?

Thanks so much for the tip on the code though...

**Comment by BBC-Esq** [comment]
BTW, when your library the correct way like you suggested, the transcription time went from 2 minutes and 8 seconds to 1 minute and 48 seconds instead!  Thanks again for the advice!

**Comment by BBC-Esq** [comment]
![image](https://github.com/shashikg/WhisperS2T/assets/108230321/bc70ab34-1d25-4798-94b8-b0913e0387ee)

**Comment by BBC-Esq** [comment]
Lack of response
