### ISSUE TITLE
have you considered using the "hotwords" concept for newer terminology?

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#49]
Basically, feed the model some words or phrases that are likely to appear but not likely to be recognized, in advance, to improve chances of accuracy:

https://github.com/SYSTRAN/faster-whisper/pull/731

**Comment by jax-explorer** [comment]
@BBC-Esq  Yes, The purpose of hotwords is to add new vocabulary or terms to the

**Comment by shashikg** [comment]
Hey, yeah I have experimented with that. The reason why added the `input_prompt` args in transcribe function. It's planned but it's experimental. I don't want to put it into early release as a gimmick for this project. Once I am satisfied with the results will release this feature.
