### ISSUE TITLE
15s of silence causes exception

### ISSUE THREAD

**Issue by eschmidbauer** [shashikg/WhisperS2T#5]
```python
import whisper_s2t

model = whisper_s2t.load_model(model_identifier="large-v2", backend='CTranslate2')

files = ['silence.wav']
lang_codes = ['en']
tasks = ['transcribe']
initial_prompts = [None]

out = model.transcribe_with_vad(files,
                                lang_codes=lang_codes,
                                tasks=tasks,
                                initial_prompts=initial_prompts,
                                batch_size=32)

print(out[0][0])
```

```bash
Transcribing:   0%|                                                                                                                                               | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/myapp/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/myapp/lib/python3.11/site-packages/whisper_s2t/backends/__init__.py", line 138, in transcribe_with_vad
    for signals, prompts, seq_len, seg_metadata, pbar_update in self.data_loader(audio_files, lang_codes, tasks, initial_prompts, batch_size=batch_size):
  File "/opt/myapp/lib/python3.11/site-packages/whisper_s2t/data.py", line 193, in get_data_loader_with_vad
    new_segmented_audio_signal = self.get_segmented_audio_signal(audio_signal, file_id, lang, task, initial_prompt)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/myapp/lib/python3.11/site-packages/whisper_s2t/data.py", line 146, in get_segmented_audio_signal
    start_ends, audio_signal = self.speech_segmenter(audio_signal=audio_signal)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/myapp/lib/python3.11/site-packages/whisper_s2t/speech_segmenter/__init__.py", line 127, in __call__
    start_ends[0][0] = max(0.0, start_ends[0][0]) # fix edges
                                ~~~~~~~~~~^^^
IndexError: list index out of range
```

[silence.wav.zip](https://github.com/shashikg/WhisperS2T/files/13820045/silence.wav.zip)

I know this sounds like an odd use-case but when processing dual channel audio (splitting, then transcribing), often the single channel can be left with silence. Is there anyway to handle this exception by returning an empty result set if no audio is detected?

**Comment by shashikg** [comment]
Hi @eschmidbauer thanks for reporting this. This seems to be a missed edge case. I am planning an another release coming weekend, will include this in the same.

Btw, were you getting any issue/error if you directly send the dual-channel audio as input, without splitting? Internal audio processing of WhisperS2T should be able to handle such cases by mixing the multi-channel into a single channel stream.

Also, what do you suggest, will it be helpful to include feature to transcribe files stream/channel wise for cases like when each channel/stream contains audio data for different speakers?

**Comment by eschmidbauer** [comment]
> Btw, were you getting any issue/error if you directly send the dual-channel audio as input, without splitting? Internal audio processing logic of WhisperS2T should be able to handle such cases by mixing the multi-channel stream into a single channel stream.

No errors when i send the dual-channel audio as input. I get back a transcription as expected. My guess is the audio is mixed into a single channel automatically, in which case, there is no silence, andthe transcription is successful. 

> Also, what do you suggest, will it be helpful to include a feature to transcribe files stream/channel wise for cases like when each channel/stream contains audio data for different speakers?

Of course, if WhisperS2T could handle dual-channel and assign speakers, that would be great. But I think the current implementation makes sense (mix the two audio streams into mono before transcribing). I wouldn't want to see this project become overly-complicated and make it too difficult for the maintainers to support. For example, you may be opening up more issues when handling dual-channel (like segment/word-alignment across channels).

**Comment by shashikg** [comment]
> I wouldn't want to see this project become overly-complicated and make it too difficult for the maintainers to support. For example, you may be opening up more issues when handling dual-channel (like segment/word-alignment across channels).

Agree! I will just add the fix for silent audio case.
