### ISSUE TITLE
Has this repository been abandoned?

### ISSUE THREAD

**Issue by BBC-Esq** [shashikg/WhisperS2T#54]
This repository was active a lot initially and then nothing for over a month.  Anyone have any idea if the repository owner has abandoned it or something?  I know that Huggingface basically tried to recruit the owner after they didn't like the fact that his program is better and/or faster than their product...maybe they got to him somehow?  lol

**Comment by shashikg** [comment]
Lol 😂 

Hi @BBC-Esq I recently switched my job and is slightly stuffed (btw it's not huggingface - and they didn't tried to recruit me) (My LinkedIn:  https://www.linkedin.com/in/shashikg in case you want to remain updated 😂). But it's not abandoned. I will still release some of awesome plans that I have for this project. But I work on it in my free time, this is not my primary work, so somethings can take time. 

PS: Please don't spread hatewords for any org in here. Huggingface is very useful tool, and I personally use it for many stuffs.

**Comment by BBC-Esq** [comment]
> Lol 😂
> 
> Hi @BBC-Esq I recently switched my job and is slightly stuffed (btw it's not huggingface - and they didn't tried to recruit me) (My LinkedIn: https://www.linkedin.com/in/shashikg in case you want to remain updated 😂). But it's not abandoned. I will still release some of awesome plans that I have for this project. But I work on it in my free time, this is not my primary work, so somethings can take time.
> 
> PS: Please don't spread hatewords for any org in here. Huggingface is very useful tool, and I personally use it for many stuffs.

Ok, sorry about the misunderstanding...Closing out this issue.
