### ISSUE TITLE
Possible to run WhisperS2T without GPU? (Issue with CUDA)

### ISSUE THREAD

**Issue by tlcameron3** [shashikg/WhisperS2T#60]
I have received this error when trying to run with CTranslate2:

Fetching 4 files: 100%|██████████| 4/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\xxx\PycharmProjects\LifeLogs\LifeLogsHandler\scripts\audio\whisper_setup.py", line 3, in <module>
    model = whisper_s2t.load_model(model_identifier="large-v2", backend='CTranslate2')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\PycharmProjects\LifeLogs\LifeLogsHandler\venv\Lib\site-packages\whisper_s2t\__init__.py", line 44, in load_model
    return WhisperModel(model_identifier, **model_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\PycharmProjects\LifeLogs\LifeLogsHandler\venv\Lib\site-packages\whisper_s2t\backends\ctranslate2\model.py", line 80, in __init__
    self.model = ctranslate2.models.Whisper(self.model_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

Process finished with exit code 1

I see that there is a way to configure CTranslate2 to not require CUDA (as I am running from a simple laptop with CPU, for testing, before running this code on some cloud processing system), but I do not know if there is a way to access that without rewriting the CTranslate2 source code?

I apologize if I am misunderstanding the problem. Thank you for your help.

Best,
tlc

**Comment by didlawowo** [comment]
i'm interested too

**Comment by NalMonMP** [comment]
It is possible to use the CPU instead of CUDA. Just give the function the respective model kwargs:

```
if not torch.cuda.is_available():
    logger.warning('Graphics card not available. Switching to CPU. Transcription will be significantly slower.')
    model_kwargs['device'] = 'cpu'
    model_kwargs['compute_type'] = "float32"
```

And then load the model:
`model = whisper_s2t.load_model(model_identifier=model, backend=backend, **kwargs)`

For reference, have a look at the model file:
[](https://github.com/shashikg/WhisperS2T/blob/main/whisper_s2t/backends/ctranslate2/model.py
)
