### ISSUE TITLE
tokenizer.json file?

### ISSUE THREAD

**Issue by tianchengcheng-cn** [shashikg/WhisperS2T#72]
I can't find tokenizer.json in this project. how to get it?

**Comment by eschmidbauer** [comment]
try here
`https://huggingface.co/Systran/faster-whisper-large-v3/raw/main/tokenizer.json`

**Comment by tianchengcheng-cn** [comment]
> try here `https://huggingface.co/Systran/faster-whisper-large-v3/raw/main/tokenizer.json`

thx
